INSERT INTO oscars (año_estreno, mejor_pelicula, mejor_director, mejor_actor, mejor_actriz)
VALUES
('1929', 'Wings', 'F. Borzage L.Milestone', 'E. Jannings', 'J. Gaynor'),
('1930', 'The Broadway Melody', 'F. Lloyd', 'W. Baxter', 'M. Pickford'),
('1930', 'All Quiet On The Western Front', 'L. Milestone', 'G. Arliss', 'M. Pickford'),
('1931', 'Cimarron', 'N. Taurog', 'L. Barrymore', 'M. Dressler'),
('1932', 'Grand Hotel', 'F. Borzage', 'F. March, W. Beery', 'H. Hayes'),
('1934', 'Cavalcade', 'F. Lloyd', 'C. Laughton', 'K. Hepburn'),
('1935', 'It Happened One Night', 'F. Capra', 'C. Gable', 'C. Colbert'),
('1936', 'Mutiny on the Bounty', 'J. Ford', 'V. McLaglen', 'B. Davis'),
('1937', 'The Great Ziegfeld', 'F. Capra', 'P. Muni', 'L. Rainer'),
('1938', 'The life of Emile Zola', 'L. McCarey', 'S. Tracy', 'L. Rainer'),
('1939', 'You Cant Take It With You', 'F. Capra', 'S. Tracy', 'B. Davis'),
('1940', 'Gone with the Wind', 'V. Fleming', 'R. Donat', 'V. Leigh'),
('1941', 'Rebecca', 'J. Ford', 'J. Stewart', 'G. Rogers'),
('1942', 'How Green Was My Valley', 'J. Ford', 'G. Cooper', 'J. Fontaine'),
('1943', 'MrS. Miniver', 'W. Wyler', 'J. Cagney', 'G. Garson'),
('1944', 'Casablanca', 'M. Curtiz', 'P. Lukas', 'J. Jones'),
('1945', 'Going My Way', 'L. McCarey', 'B. Crosby', 'I. Bergman'),
('1946', 'The Lost Weekend', 'B. Wilder', 'R. Milland', 'J. Crawford'),
('1947', 'The Best Years of Our Lives', 'W. Wyler', 'F. March', 'O. de Havilland'),
('1948', 'Gentlemans Agreement', 'E. Kazan', 'R. Colman', 'L. Young'),
('1949', 'Hamlet', 'J. Huston', 'L. Olivier', 'J. Wyman'),
('1950', 'All the Kings Men', 'J. Mankiewicz', 'B. Crawford', 'O. de Havilland'),
('1951', 'All About Eve', 'J. Mankiewicz', 'J. Ferrer', 'J. Holliday'),
('1952', 'An American in Paris', 'G. Stevens', 'H. Bogart', 'V. Leigh'),
('1953', 'The Greatest Show on Earth', 'J. Ford', 'G. Cooper', 'S. Booth'),
('1954', 'From Here to Eternity', 'F. Zinnemann', 'W. Holden', 'A. Hepburn'),
('1955', 'On the Waterfront', 'E. Kazan', 'M. Brando', 'G. Kelly'),
('1956', 'Marty', 'D. Mann', 'E. Borgnine', 'A. Magnani'),
('1957', 'Around the World in 80 Days', 'G. Stevens', 'Y. Brynner', 'I. Bergman'),
('1958', 'The Bridge on the River Kwai', 'D. Lean', 'A. Guinness', 'J. Woodward'),
('1959', 'Gigi', 'V. Minnelli', 'D. Niven', 'S. Hayward'),
('1960', 'Ben-Hur', 'W. Wyler', 'C. Heston', 'S. Signoret'),
('1961', 'The Apartment', 'B. Wilder', 'B. Lancaster', 'E. Taylor'),
('1962', 'West Side Story', 'R. Wise, J. Robbins', 'M. Schell', 'S. Loren'),
('1963', 'Lawrence of Arabia', 'D. Lean', 'G. Peck' , 'A. Bancroft'),
('1964', 'Tom Jones', 'T. Richardson', 'S. Poitier', 'P. Neal'),
('1965', 'My Fair Lady', 'G. Cukor', 'R. Harrison', 'J. Andrews'),
('1966', 'The Sound of Music', 'R. Wise', 'L. Marvin', 'J. Christie'),
('1967', 'A Man for All Seasons', 'F. Zinnemann', 'P. Scofield', 'E. Taylor'),
('1968', 'In the Heat of the Night', 'M. Nichols', 'R. Steiger', 'K. Hepburn'),
('1969', 'Oliver!', 'C. Reed', 'C. Robertson', 'K. Hepburn''B. Streisand'),
('1970', 'Midnight Cowboy', 'J. Schlesinger', 'John Wayne', 'M. Smith'),
('1971', 'Patton', 'F. Schaffner', 'G. C. Scott', 'G. Jackson'),
('1972', 'The French Connection', 'W. Friedkin', 'G. Hackman', 'J. Fonda'),
('1973', 'The Godfather', 'B. Fosse', 'M. Brando', 'L. Minnelli'),
('1974', 'The Sting', 'G. R. Hill', 'J. Lemmon', 'G. Jackson'),
('1975', 'El padrino II', 'F. F. Coppola', 'A. Carney', 'E. Burstyn'),
('1976', 'One Flew Over the Cuckoos Nest', 'M. Forman', 'J. Nicholson', 'L. Fletcher'),
('1977', 'Rocky', 'J. G. Avildsen', 'P. Finch', 'F. Dunaway'),
('1978', 'Annie Hall', 'W. Allen', 'R. Dreyfuss', 'D. Keaton'),
('1979', 'The Deer Hunter', 'M. Cimino', 'J. Voight', 'J. Fonda'),
('1980', 'Kramer vs. Kramer', 'R. Benton', 'D. Hoffman', 'S. Field'),
('1981', 'Ordinary People', 'R. Redford', 'R. De Niro', 'S. Spacek'),
('1982', 'Chariots of Fire', 'W. Beatty', 'H. Fonda', 'K. Hepburn'),
('1983', 'Gandhi', 'R. Attenborough', 'R. Duvall', 'M. Streep'),
('1984', 'Terms of Endearment', 'J. L. Brooks', 'R. Duvall', 'S. MacLaine'),
('1985', 'Amadeus', 'M. Forman', 'F. M. Abraham', 'S. Field'),
('1986', 'Out of Africa', 'S. Pollack', 'W. Hurt', 'G. Page'),
('1987', 'Platoon', 'O. Stone', 'P. Newman', 'M. Matlin'),
('1988', 'The Last Emperor', 'B. Bertolucci', 'M. Douglas', 'Cher'),
('1989', 'Rain Man', 'B. Levinson', 'D. Hoffman', 'J. Foster'),
('1990', 'Driving Miss Daisy', 'O. Stone', 'D. Day-Lewis', 'J. Tandy'),
('1991', 'Dances with Wolves', 'K. Costner', 'J. Irons', 'K. Bates'),
('1992', 'The Silence of the Lambs', 'J. Demme', 'A. Hopkins', 'J. Foster'),
('1993', 'Unforgiven', 'C. Eastwood', 'A. Pacino', 'E. Thompson'),
('1994', 'Schindlers List', 'S. Spielberg', 'T. Hanks', 'H. Hunter'),
('1995', 'Forrest Gump', 'R. Zemeckis', 'T. Hanks', 'J. Lange'),
('1996', 'Braveheart', 'M. Gibson', 'N. Cage', 'S. Sarandon'),
('1997', 'The English Patient', 'A. Minghella', 'G. Rush', 'F. McDormand'),
('1998', 'Titanic', 'J. Cameron', 'J. Nicholson', 'H. Hunt'),
('1999', 'Shakespeare in Love', 'S. Spielberg', 'R. Benigni', 'G. Paltrow'),
('2000', 'American Beauty', 'S.Mendes', 'K. Spacey', 'H. Swank'),
('2001', 'Gladiator', 'S. Soderbergh', 'R. Crowe', 'J. Roberts'),
('2002', 'A Beautiful Mind', 'R. Howard', 'D. Washington', 'H. Berry'),
('2003', 'Chicago', 'R. Polanski', 'A. Brody', 'N. Kidman'),
('2004', 'The Lord of the Rings: The Return of the King', 'P. Jackson', 'S. Penn', 'C. Theron'),
('2005', 'Million Dollar Baby', 'C. Eastwood',	'J. Foxx',	'H. Swank'),
('2006', 'Crash', 'A. Lee', 'P. S. Hoffman', 'R. Witherspoon'),
('2007', 'The Departed', 'M. Scorsese', 'F. Whitaker', 'H. Mirren'),
('2008', 'No Country for Old Men', 'J. Coen E. Coen', 'D. Day-Lewis', 'M. Cotillard'),
('2009', 'Slumdog Millionaire', 'D. Boyle', 'S. Penn', 'K. Winslet'),
('2010', 'The Hurt Locker', 'K. Bigelow', 'J. Bridges', 'S. Bullock'),
('2011', 'The Kings Speech', 'T. Hooper', 'C. Firth', 'N. Portman'),
('2012', 'The Artist', 'M. Hazanavicius', 'J. Dujardin', 'M. Streep'),
('2013', 'Argo', 'A. Lee', 'D. Day-Lewis', 'J. Lawrence'),
('2014', '12 Years a Slave', 'A. Cuarón', 'M. McConaughey', 'C. Blanchett'),
('2015', 'Birdman', 'A. G. Iñárritu', 'E. Redmayne', 'J.Moore'),
('2016', 'Spotlight', 'A. G. Iñárritu', 'L. DiCaprio', 'B. Larson'),
('2017', 'Moonlight',	'D. Chazelle', 'C. Affleck', 'E. Stone'),
('2018', 'The Shape of Water', 'G. del Toro', 'G. Oldman', 'F. McDormand'),
('2019', 'Green Book', 'A. Cuarón', 'R. Malek', 'O. Colman'),
('2020', 'Parasite', 'Bong J.', 'J. Phoenix', 'R. Zellweger'),
('2021', 'Nomadland', 'C. Zhao', 'A. Hopkins', 'F. McDormand'),
('2022', 'CODA', 'J. Campion', 'W. Smith', 'J. Chastain'),
('2023', 'Everything Everywhere All at Once', 'D. Kwan D. Scheinert', 'B. Fraser', 'M. Yeoh'),
('2024', 'Oppenheimer', 'C. Nolan', 'C. Murphy', 'E. Stone');


















